/**
 * -------------------------------------------------------
 * DO NOT EDIT THIS FILE!
 * Use ./gruntConfig.js instead.
 * -------------------------------------------------------
 */

var path = require( 'path' ),
    config = require( './gruntConfig.js' ),
    internals = require( './gruntInternals.js' );


module.exports = function(grunt) {
    grunt.initConfig( {
        pkg: grunt.file.readJSON( 'package.json' ),
        clean: internals.clean,
        browserify: internals.modules.browserify,
        htmlbuild: internals.modules.htmlBuild,
        copy: internals.modules.copy,
        htmlmin: internals.modules.htmlMin,
        uglify: internals.modules.uglify,
        cssmin: internals.modules.cssMin,
        watch: internals.modules.watch,
        connect: internals.modules.connect
    } );

    grunt.loadNpmTasks( 'grunt-contrib-connect' );
    grunt.loadNpmTasks( 'grunt-contrib-clean' );
    grunt.loadNpmTasks( 'grunt-browserify' );
    grunt.loadNpmTasks( 'grunt-html-build' );
    grunt.loadNpmTasks( 'grunt-contrib-copy' );
    grunt.loadNpmTasks( 'grunt-contrib-htmlmin' );
    grunt.loadNpmTasks( 'grunt-contrib-cssmin' );
    grunt.loadNpmTasks( 'grunt-contrib-uglify' );
    grunt.loadNpmTasks( 'grunt-contrib-watch' );

    grunt.registerTask( 'default', internals.taskList );
};